version: '3.8'

services:
  hom-mongodb:
    image: mongo
    ports:
      - "27018:27017"
    deploy:
      resources:
        limits:
          memory: 350m
  hom-mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=test-review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
  rabbitmq:
    image: rabbitmq:3.8.11-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60
    deploy:
      resources:
        limits:
          memory: 512m
