version: '3.7'

services:
  hom-prod-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 350m

  hom-prod-mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd

  product:
    build: microservices/product-service
    deploy:
      resources:
        limits:
          memory: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - hom-prod-mongodb

  recommendation:
    build: microservices/recommendation-service
    deploy:
      resources:
        limits:
          memory: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - hom-prod-mongodb

  review:
    build: microservices/review-service
    deploy:
      resources:
        limits:
          memory: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - hom-prod-mysql

  product-composite:
    build: microservices/product-composite-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
