spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: test-mongo-db
      auto-index-creation: true
  cloud:
    stream:
      bindings:
        input:
          destination: products
          group: productsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
            partitioned: true
            instance-index: 0
      rabbit:
        bindings:
          input:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        bindings:
          input:
            consumer:
              enable-dlq: true

server:
  port: 7001
  error:
    include-message: always


logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: hom-prod-mongodb
      port: 27017

server:
  port: 8080

