spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      host: localhost
      port: 27018
      database: test-prod-db

server:
  port: 7001
  error:
    include-message: always


logging:
  level:
    root: INFO
    se.magnus: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

