spring:
  config:
    activate:
      on-profile: local

server:
  port: 7001
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
#spring:
#  profiles:
#    docker

server:
  port: 8080

