spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test-review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 7003
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/review-db
  rabbitmq:
    host: rabbitmq
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
      default-binder: rabbit


server:
  port: 8080
