#spring:
#  profiles:
#    active: test
#
#---

#spring:
#  config:
#    activate:
#      on-profile: test
#  datasource:
#    url: jdbc:mysql://localhost/review-db
#    username: user
#    password: pwd
#    hikari:
#      initialization-fail-timeout: 60000

server:
  port: 7003
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080
